 const roles=p=>playerRoles(p||{},state.auction?.settings?.fantasy_mode||'classic').map(r=>r==='P'?'Por':r);
 const known=()=>{const m=new Map(),add=p=>p?.id&&m.set(String(p.id),p);(state.list?.players||[]).forEach(add);(state.auction?.callCandidates||[]).forEach(add);add(state.auction?.currentPlayer);(state.auctionPersonalRoster?.assignments||[]).forEach(x=>add(x.player));return[...m.values()]};
 function merge(){known().forEach(p=>{const f=state.v8Features.get(String(p.id))||state.v8Features.get(String(p.source_player_id||''));if(f)p.strategic_features=f})}
 async function hydrate(force=false){const lid=state.selectedLeague?.id||'';if(!lid||state.v8Busy||(!force&&state.v8League===lid&&state.v8Features.size))return merge();state.v8Busy=1;try{const[a,b,c]=await Promise.all([sapi({action:'getProfile'}),sapi({action:'getStrategicFeatures'}),api(ENDPOINTS.v6y,{action:'getPreferences'},{quiet:true})]);state.v8League=lid;state.v8Profile=a?.profile||state.v8Profile;state.v8Modules=a?.mantraModules||MOD;state.v8Features=new Map();(b?.players||[]).forEach(x=>{state.v8Features.set(String(x.id),x.strategic_features||{});state.v8Features.set(String(x.source_player_id),x.strategic_features||{})});if(c?.preferences)state.v7Preferences=new Map(c.preferences.map(x=>[String(x.source_player_id),x]));state.v7Stats=new Map();merge()}catch(e){console.warn('V8 hydrate',e)}finally{state.v8Busy=0}}
 const weight=p=>fm(p)*(.82+.18*prs(p)/100)*(1-.06*vol(p));
 function best(ps,id){const slots=state.v8Modules[id]||MOD[id];if(!slots)return null;let dp=Array(1<<slots.length).fill(null);dp[0]={s:0,l:Array(slots.length).fill(null)};for(const p of ps){const nx=dp.slice(),rr=new Set(roles(p));for(let m=0;m<dp.length;m++){const cur=dp[m];if(!cur)continue;for(let i=0;i<slots.length;i++){const bit=1<<i;if(m&bit||!slots[i].some(r=>rr.has(r)))continue;const nm=m|bit,sc=cur.s+weight(p);if(!nx[nm]||sc>nx[nm].s){const l=cur.l.slice();l[i]=p;nx[nm]={s:sc,l}}}}dp=nx}let bm=0,b=dp[0];for(let m=1;m<dp.length;m++){if(!dp[m])continue;if(pop(m)>pop(bm)||(pop(m)===pop(bm)&&dp[m].s>b.s)){bm=m;b=dp[m]}}const lp=(b?.l||[]).filter(Boolean),avg=f=>lp.length?lp.reduce((s,p)=>s+f(p),0)/lp.length:0;return{id,completion:Math.round(pop(bm)/slots.length*100),fantasy:avg(fm),presence:avg(prs),volatility:avg(vol),flex:lp.length?lp.reduce((s,p)=>s+Math.min(3,new Set(roles(p)).size),0)/(lp.length*3):0,lineup:b?.l||[]}}
 const mids=()=>{const a=(state.v8Profile?.preferred_modules||[]).filter(x=>state.v8Modules[x]);return a.length?a:Object.keys(state.v8Modules||MOD)};
 const solid=b=>b?Math.round(cl(b.completion/100*.25+b.presence/100*.42+b.flex*.18+(1-b.volatility)*.15,0,1)*100):0;
 function metrics(info,extra=null){if(!info)return{completion:0,fantasy:0,solidity:0,module:null};const ps=(info.assignments||[]).map(x=>x.player).filter(Boolean);if(extra&&!ps.some(p=>p.id===extra.id))ps.push(extra);if((state.auction?.settings?.fantasy_mode||'classic')!=='mantra'){const lim=Math.max(1,Number(info.rosterLimit||info.rosterMin||25)),top=ps.slice().sort((a,b)=>weight(b)-weight(a)).slice(0,11),fa=top.length?top.reduce((s,p)=>s+fm(p),0)/top.length:0,pr=top.length?top.reduce((s,p)=>s+prs(p),0)/top.length:0,vo=top.length?top.reduce((s,p)=>s+vol(p),0)/top.length:1;return{completion:Math.round(Math.min(1,ps.length/lim)*100),fantasy:fa,solidity:Math.round(cl(pr/100*.65+(1-vo)*.35,0,1)*100),module:null}}const arr=mids().map(id=>best(ps,id)).filter(Boolean).sort((a,b)=>b.completion-a.completion||b.fantasy-a.fantasy),b=arr[0];return{completion:b?.completion||0,fantasy:b?.fantasy||0,solidity:solid(b),module:b?.id||null,formation:b}}
 function baseMetric(info){const k=[...(info?.assignments||[]).map(x=>`${x.id||x.player?.id}:${x.purchase_price||0}`),...(state.v8Profile?.preferred_modules||[])].join('|');if(state.v8MetricKey===k&&state.v8Metric)return state.v8Metric;state.v8MetricKey=k;return state.v8Metric=metrics(info)}
 function anchors(info){const a=info?.assignments||[];if(!a.length)return[];const av=a.reduce((s,x)=>s+Number(x.purchase_price||0),0)/a.length;return a.filter(x=>{const p=x.player||{},ref=Number(p.pfc||p.pma||p.quotation||0);return Number(p.slot||99)<=2&&fm(p)>=5.7&&prs(p)>=60&&Number(x.purchase_price||0)>=Math.max(av*1.15,ref*.8)})}
 function quick(p){const info=auctionMyTeamDashboardData();if(!info)return{completionDelta:0,fantasyDelta:0,solidityDelta:0,anchorFit:0};const rr=roles(p),cnt=new Map();(info.assignments||[]).flatMap(x=>roles(x.player)).forEach(r=>cnt.set(r,(cnt.get(r)||0)+1));const rare=rr.length?Math.max(...rr.map(r=>Math.max(0,3-(cnt.get(r)||0)))):0,aa=anchors(info),ar=new Set(aa.flatMap(x=>roles(x.player))),rep=rr.some(r=>ar.has(r));return{completionDelta:rare*2+Math.min(3,new Set(rr).size),fantasyDelta:Math.max(0,fm(p)-5.5)*.08,solidityDelta:Math.round((prs(p)-55)/15),anchorFit:aa.length?(rep&&!rare?-3:rare>=2?5:1):0}}
 function impact(p){const info=auctionMyTeamDashboardData();if(!info)return quick(p);const before=baseMetric(info),after=metrics(info,p),aa=anchors(info);let af=0;if(aa.length){if(after.completion>before.completion)af+=7;if(after.fantasy>before.fantasy+.03)af+=5;if(after.solidity>before.solidity)af+=4;const rr=new Set(roles(p)),ov=aa.some(x=>roles(x.player).some(r=>rr.has(r)));if(ov&&after.completion===before.completion&&after.fantasy<=before.fantasy+.02)af-=4}return{completionDelta:after.completion-before.completion,fantasyDelta:after.fantasy-before.fantasy,solidityDelta:after.solidity-before.solidity,anchorFit:af,before,after}}
 function market(p){const rr=new Set(roles(p)),a=(state.auction?.recentAwards||[]).filter(x=>{const q=x.player||{},ref=Number(q.pfc||q.pma||q.quotation||0),pr=Number(x.price||x.amount||0);return ref>0&&pr>0&&roles(q).some(r=>rr.has(r))}).slice(0,12).map(x=>cl(Number(x.price||x.amount)/Number(x.player?.pfc||x.player?.pma||x.player?.quotation||1),.55,1.65));return a.length?cl(a.reduce((s,x)=>s+x,0)/a.length,.75,1.3):1}
 function opp(p,i){const pf=pref(p),mk=market(p),sl=Number(p.slot||99);return Math.round(cl(43+trend(p)*13+(prs(p)-60)*.16+(sl<=1?9:sl===2?6:sl===3?3:0)+Math.max(0,i.completionDelta)*.55+Math.max(-8,Math.min(12,i.fantasyDelta*18))+i.anchorFit+(mk<.95?(.95-mk)*35:-(mk-1.05)*16)+(pf?.strategy==='top'?9:pf?.is_favorite?4:pf?.strategy==='avoid'?-35:0),0,100))}
 function prices(p,score,o){const info=auctionMyTeamDashboardData(),pf=pref(p),ref=Math.max(1,Number(p.pfc||p.pma||p.quotation||1)),mk=market(p),prf=state.v8Profile?.profile||'balanced',mult=prf==='aggressive'?1.06:prf==='conservative'?.95:1,q=1+cl(trend(p),-.15,.15)*.25+(prs(p)/100-.65)*.08;let s=Math.max(1,Math.round(ref*mk*q*(.93+o/100*.15)*mult)),c=Math.max(s,Math.round(s*(1.10+Math.max(0,score-65)/500)));if(pf?.expected_spend!=null)s=Math.max(1,Math.round((s*2+Number(pf.expected_spend))/3));if(pf?.max_price!=null)c=Math.min(c,Math.max(1,Number(pf.max_price)));const mb=Number(info?.maxBid);if(Number.isFinite(mb)){c=Math.min(c,Math.max(0,mb));s=Math.min(s,c)}return{suggested:s,ceiling:c,marketFactor:mk}}
 const oldScore=auctionSuggestedCallScore;auctionSuggestedCallScore=function(p){state.v7Stats=new Map();const x=oldScore(p);if(!x)return null;const i=quick(p),o=opp(p,i);x.score=cl(x.score+Math.round(trend(p)*15)+Math.round((prs(p)-60)*.08)+Math.round(Math.max(0,i.completionDelta)*.22)+Math.round(i.fantasyDelta*12)+Math.round(i.solidityDelta*.16)+i.anchorFit+Math.round((o-50)*.12),0,100);x.opportunity=o;x.rosterImpact=i;x.features=feat(p);x.prices=prices(p,x.score,o);return x};
 const oldCalls=auctionSuggestedCalls;function rows(limit){const a=oldCalls(Math.max(12,limit)).map(x=>{const i=impact(x.player),o=opp(x.player,i);x.rosterImpact=i;x.opportunity=o;x.score=cl(Number(x.score||0)+Math.round(Math.max(0,i.completionDelta)*.30)+Math.round(i.fantasyDelta*14)+Math.round(i.solidityDelta*.18)+i.anchorFit,0,100);x.prices=prices(x.player,x.score,o);return x}).sort((a,b)=>b.score-a.score||b.opportunity-a.opportunity);if(!a.length)return[];const info=auctionMyTeamDashboardData(),ctx=[auctionSession()?.id||'',state.auction?.auctionSession?.role_phase_index||0,info?.assignments?.length||0].join('|'),cur=a.find(x=>String(x.player?.id)===String(state.v8Moment||'')),ch=a[0];if(state.v8MomentCtx!==ctx||!cur||ch.score>=cur.score+9){state.v8MomentCtx=ctx;state.v8Moment=ch.player?.id}const m=a.find(x=>String(x.player?.id)===String(state.v8Moment||''))||ch;return[m,...a.filter(x=>x!==m)].slice(0,limit)}
 function conv(x,y){const gap=Math.max(0,Number(x?.score||0)-Number(y?.score||0)),v=Math.round(cl(48+Number(x?.opportunity||50)*.28+gap*2.1+Number(x?.rosterImpact?.completionDelta||0)*.22,0,100));return{v,label:v>=82?'MOLTO ALTA':v>=68?'ALTA':v>=52?'MEDIA':'PRUDENTE'}}
 function objective(info,extra=null,cost=0){if(!info)return metrics(info,extra);const ps=(info.assignments||[]).map(x=>x.player).filter(Boolean);if(extra)ps.push(extra);let budget=Math.max(0,Number(info.remaining||0)-Number(cost||0)),max=Math.max(ps.length,Number(info.rosterMin||info.rosterLimit||25)),owned=new Set(ps.map(p=>String(p.id))),cand=(state.auction?.callCandidates||[]).filter(p=>!owned.has(String(p.id))).map(p=>{const o=opp(p,quick(p)),pr=prices(p,60,o).suggested;return{p,pr,v:weight(p)+o/40+Math.max(0,4-Number(p.slot||4))*.15}}).sort((a,b)=>b.v-a.v).slice(0,45);for(const c of cand){if(ps.length>=max)break;const reserve=Math.max(0,max-ps.length-1);if(c.pr+reserve>budget)continue;ps.push(c.p);budget-=c.pr}return metrics({...info,assignments:ps.map(p=>({player:p}))})}
